/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudgetBudgetIdRouteImport } from './routes/budget/$budgetId'
import { Route as BudgetNewRouteImport } from './routes/budget/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetBudgetIdRoute = BudgetBudgetIdRouteImport.update({
  id: '/budget/$budgetId',
  path: '/budget/$budgetId',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetNewRoute = BudgetNewRouteImport.update({
  id: '/budget/new',
  path: '/budget/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget/$budgetId': typeof BudgetBudgetIdRoute
  '/budget/new': typeof BudgetNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget/$budgetId': typeof BudgetBudgetIdRoute
  '/budget/new': typeof BudgetNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget/$budgetId': typeof BudgetBudgetIdRoute
  '/budget/new': typeof BudgetNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/budget/$budgetId' | '/budget/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/budget/$budgetId' | '/budget/new'
  id: '__root__' | '/' | '/budget/$budgetId' | '/budget/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetBudgetIdRoute: typeof BudgetBudgetIdRoute
  BudgetNewRoute: typeof BudgetNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget/$budgetId': {
      id: '/budget/$budgetId'
      path: '/budget/$budgetId'
      fullPath: '/budget/$budgetId'
      preLoaderRoute: typeof BudgetBudgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget/new': {
      id: '/budget/new'
      path: '/budget/new'
      fullPath: '/budget/new'
      preLoaderRoute: typeof BudgetNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetBudgetIdRoute: BudgetBudgetIdRoute,
  BudgetNewRoute: BudgetNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
